#!/bin/bash

mkdir ~/.dt 2> /dev/null

touch ~/.dt/table

TABLE_CONTENT="home $HOME"
SCRIPT_MAGIC=$(cat script_magic)
FUNCTION_MAGIC=$(cat function_magic)

# See whether the user has a 'home' tag.
grep -i "home " $HOME/.dt/table > /dev/null
ret=$?

if [ $ret == 0 ]; then
  echo "Initial tag 'home' already in the table."
else
  echo "Initial tag 'home' not found; appending."
  echo "$TABLE_CONTENT" >> ~/.dt/table
fi

echo -e "Writing main script '~/.dt/dt_script'..."
echo -e "$SCRIPT_MAGIC" > ~/.dt/dt_script
echo -e "Writing main script done!"

grep "function dt" ~/.bashrc > /dev/null
ret=$?

if [ $ret == 0 ]; then
  echo "Function magic already in .bashrc"
else
  echo -e "Writing function magic to .bashrc.\nPlease reload by typing '. ~/.bashrc'"
  echo -e "$FUNCTION_MAGIC" >> ~/.bashrc
fi

grep "function dt" ~/.bash_profile > /dev/null
ret=$?

if [ $ret == 0 ]; then
  echo "Function magic already in .bash_profile"
else
  echo -e "Writing function magic to .bash_profile."
  echo -e "$FUNCTION_MAGIC" >> ~/.bash_profile
fi

